version: '3'
services:
  ktechnics/ktechnics-api:
    image: omollo/ktechnics/ktechnics-api-prod
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.3"
          memory: 200M
    ports: 
      - "9001:9001"
      - "9002:9002"
      - "9003:9003"
    networks:
      - host
    volumes:
      - logs:/go/logs

volumes:
  logs:

# Networks to be created to facilitate communication between containers
networks:
  host:

