version: '3'
services:
  ktechnics-api-portal:
    image: omollo/ktechnics-api-prod
    deploy:
      replicas: 1
    ports: 
      - "9001:9001"
      - "9002:9002"
      - "9003:9003"
    networks:
      - host
    volumes:
      - logs:/go/logs
    depends_on:
      - "mysql-db"
      - "redis"

  mysql-db:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    container_name: mysql
    restart: always
    volumes:
      - db-data:/var/lib/mysql
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      - MYSQL_ROOT_PASSWORD=ktech-2030
      - MYSQL_USER=remote
      - MYSQL_PASSWORD=ktech-2030
      - MYSQL_DATABASE=ktechnics_portal
      - TZ = Africa/Nairobi
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: "/etc/init.d/mysql status"
      interval: 1s
      retries: 120
    ports:
      - "3306:3306"
    expose:
      - 3306
  
  redis:
    image: "redis:alpine"
    hostname: redis
    ports:
      - "6379:6379"
  
volumes:
  logs:
  db-data:
    driver: local

# Networks to be created to facilitate communication between containers
networks:
  host:

