version: '3'
services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ktech-2030
      MYSQL_DATABASE: ktechnics_portal
      MYSQL_USER: remote
      MYSQL_PASSWORD: ktech-2030
      TZ: 'Africa/Nairobi'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./mysql-volume:/var/lib/mysql
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - 3306:3306

  ktechnics-api-portal:
    image: omollo/ktechnics-api-prod
    restart: always
    deploy:
      replicas: 1
    ports: 
      - "9001:9001"
      - "9002:9002"
      - "9003:9003"
    volumes:
      - logs:/go/logs
    depends_on:
      - db
      - redis
      - mongodb_container
    environment:
      - WAIT_HOSTS=db:3306
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=30
      - WAIT_HOST_CONNECT_TIMEOUT=30
  
  mongodb_container:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: safcom2012
    ports:
      - 27017:27017
    volumes:
      - ./mongodb_data_container:/data/db
  redis:
    image: "redis:alpine"
    hostname: redis
    ports:
      - "6379:6379"
  
volumes:
  mysql-volume:
  logs:
  mongodb_data_container:
  


